<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dvrk_config_iros26</name>
  <version>0.1.0</version>
  <description>dVRK IROS 2026 configuration files and OAK camera utilities.</description>
  <maintainer email="anton.deguet@jhu.edu">Anton Deguet</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>dvrk_robot</exec_depend>
  <exec_depend>dvrk_console</exec_depend>
  <exec_depend>dvrk_newton</exec_depend>
  <exec_depend>dvrk_pybullet</exec_depend>
  <exec_depend>dvrk_simulator_base</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-gi</exec_depend>
  <exec_depend>gstreamer1.0</exec_depend>
  <exec_depend>gstreamer1.0-plugins-base</exec_depend>
  <exec_depend>gstreamer1.0-plugins-bad</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
